name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo apt update
          sudo apt install curl mtools squashfs-tools grub-pc-bin grub-efi xorriso debootstrap -y
          sudo bash pacperro-iso-builder-xfce.sh
          sudo mkdir -p /output
          sudo mv *.iso /output/


      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "main"
          prerelease: false
          title: "Build"
          files: |
            /output/*

